version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 1G

    networks:
      - postgres-network

    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=256MB"]

volumes:
  postgres-data:
    driver: local

networks:
  postgres-network:
    driver: bridge